### ISSUE TITLE
Training problem about data loading

### ISSUE THREAD

**Issue by BIGFatming** [vita-epfl/UniTraj#15]
I had processed AV2, nuplan and nuscenes data using the ScenarioNet, and got .pkl files. When I tried to start the training, the console outputs errors repeatedly. The output error for the nuplan dataset is:
![截图 2024-07-27 15-30-13](https://github.com/user-attachments/assets/22bf2714-5d2c-4068-870c-4cb67c347eaa)
The output error for the AV2 dataset is:
![截图 2024-07-27 15-33-09](https://github.com/user-attachments/assets/fd346903-77fa-43d1-a16d-cb2249743ac9)
And there is **NO** output errors for nuscenes!

It seems that the errors are raised by these codes in _unitraj/datasets/base_dataset.py_:
            try:
                output = self.preprocess(scenario)
                output = self.process(output)
                output = self.postprocess(output)
            except Exception as e:
                print('Error: {} in {}'.format(e, file_name))
                output = None

I ran the train.py in debug mode and removed the try except section. I did not find the difference between those scenario that trigger errors and those scenario that do not trigger.
Are these errors normal? If not, what kind of mistake may I have made during generating these data?

**Comment by Alan-LanFeng** [comment]
error in nuplan is a bug and has been fixed.
error messages in other datasets except nuscenes are normal. This is because the data is split in the time dimension (21 past, 60 future). When there is no valid agent at the current time step it raises an error.

**Comment by ChengkaiYang** [comment]
> I had processed AV2, nuplan and nuscenes data using the ScenarioNet, and got .pkl files. When I tried to start the training, the console outputs errors repeatedly. The output error for the nuplan dataset is: ![截图 2024-07-27 15-30-13](https://private-user-images.githubusercontent.com/73275810/352707553-22bf2714-5d2c-4068-870c-4cb67c347eaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjI0MjcsIm5iZiI6MTcyMjQyMjEyNywicGF0aCI6Ii83MzI3NTgxMC8zNTI3MDc1NTMtMjJiZjI3MTQtNWQyYy00MDY4LTg3MGMtNGNiNjdjMzQ3ZWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEwMzUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2OGY0ODE2NjAxMjMwY2ZhM2RhN2IxODUyYTcxYTY4MTk4ZjNiMDE0ZjRmYjI2ZDYzODY2OWM4ZDcyYjFmM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bl9s_iE-JGO6YZRlPWmaULWmAluhB5Rue-dpztoPJtA) The output error for the AV2 dataset is: ![截图 2024-07-27 15-33-09](https://private-user-images.githubusercontent.com/73275810/352707673-fd346903-77fa-43d1-a16d-cb2249743ac9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjI0MjcsIm5iZiI6MTcyMjQyMjEyNywicGF0aCI6Ii83MzI3NTgxMC8zNTI3MDc2NzMtZmQzNDY5MDMtNzdmYS00M2QxLWExNmQtY2IyMjQ5NzQzYWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEwMzUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YjkxMjdiZTJmMTg2ZGFkMWEyYmU2ODkwMDI3NWM4NWFjZGRiN2UwMTc1N2ZhYThiNmVmZmVkMzRjMjJjZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zzKsUSMXoZ36MI-ia4XT1yTk9QngYKlw5tF5eKZMxpc) And there is **NO** output errors for nuscenes!
> 
> It seems that the errors are raised by these codes in _unitraj/datasets/base_dataset.py_: try: output = self.preprocess(scenario) output = self.process(output) output = self.postprocess(output) except Exception as e: print('Error: {} in {}'.format(e, file_name)) output = None
> 
> I ran the train.py in debug mode and removed the try except section. I did not find the difference between those scenario that trigger errors and those scenario that do not trigger. Are these errors normal? If not, what kind of mistake may I have made during generating these data?
Hello, although i am not the author ,but i have noticed the project for a long time.I think Argoverse2 dataset can not use default config file provided by the project because AV2 dataset gives us 50 past trajectory points to predict 60 future trajectory points. The default config of past_len is 20, i think you should change it to 50 to avoid warning "No center objects at timestep 20".Moreover, you should change only_train_on_ego from True to False as well, if only_train_on_ego  is set True, the track object we predict is "AV" BUT AV2 official datasets may not gaurantee AV object at 50 time step is valid. In fact, official AV2 dataset want us to predict focal_object_id but not AV object so we may set only_train_on_ego to False.In fact, focal_object_id may contain not only VEHICLE type, so you may set "object_type" settings to [ 'UNSET', 'VEHICLE', 'PEDESTRIAN', 'CYCLIST', 'OTHER'] as well. Hope to cancel your warnings!

**Comment by ChengkaiYang** [comment]
> I had processed AV2, nuplan and nuscenes data using the ScenarioNet, and got .pkl files. When I tried to start the training, the console outputs errors repeatedly. The output error for the nuplan dataset is: ![截图 2024-07-27 15-30-13](https://private-user-images.githubusercontent.com/73275810/352707553-22bf2714-5d2c-4068-870c-4cb67c347eaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjI0MjcsIm5iZiI6MTcyMjQyMjEyNywicGF0aCI6Ii83MzI3NTgxMC8zNTI3MDc1NTMtMjJiZjI3MTQtNWQyYy00MDY4LTg3MGMtNGNiNjdjMzQ3ZWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEwMzUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2OGY0ODE2NjAxMjMwY2ZhM2RhN2IxODUyYTcxYTY4MTk4ZjNiMDE0ZjRmYjI2ZDYzODY2OWM4ZDcyYjFmM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bl9s_iE-JGO6YZRlPWmaULWmAluhB5Rue-dpztoPJtA) The output error for the AV2 dataset is: ![截图 2024-07-27 15-33-09](https://private-user-images.githubusercontent.com/73275810/352707673-fd346903-77fa-43d1-a16d-cb2249743ac9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjI0MjcsIm5iZiI6MTcyMjQyMjEyNywicGF0aCI6Ii83MzI3NTgxMC8zNTI3MDc2NzMtZmQzNDY5MDMtNzdmYS00M2QxLWExNmQtY2IyMjQ5NzQzYWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEwMzUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YjkxMjdiZTJmMTg2ZGFkMWEyYmU2ODkwMDI3NWM4NWFjZGRiN2UwMTc1N2ZhYThiNmVmZmVkMzRjMjJjZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zzKsUSMXoZ36MI-ia4XT1yTk9QngYKlw5tF5eKZMxpc) And there is **NO** output errors for nuscenes!
> 
> It seems that the errors are raised by these codes in _unitraj/datasets/base_dataset.py_: try: output = self.preprocess(scenario) output = self.process(output) output = self.postprocess(output) except Exception as e: print('Error: {} in {}'.format(e, file_name)) output = None
> 
> I ran the train.py in debug mode and removed the try except section. I did not find the difference between those scenario that trigger errors and those scenario that do not trigger. Are these errors normal? If not, what kind of mistake may I have made during generating these data?

Hello, although i am not the author ,but i have noticed the project for a long time.I think Argoverse2 dataset can not use default config file provided by the project because AV2 dataset gives us 50 past trajectory points to predict 60 future trajectory points. The default config of past_len is 20, i think you should change it to 50 to avoid warning "No center objects at timestep 20".Moreover, you should change only_train_on_ego from True to False as well, if only_train_on_ego is set True, the track object we predict is "AV" BUT AV2 official datasets may not gaurantee AV object at 50 time step is valid. In fact, official AV2 dataset want us to predict focal_object_id but not AV object so we may set only_train_on_ego to False.In fact, focal_object_id may contain not only VEHICLE type, so you may set "object_type" settings to [ 'UNSET', 'VEHICLE', 'PEDESTRIAN', 'CYCLIST', 'OTHER'] as well. Hope to cancel your warnings!
