### ISSUE TITLE
Clipping Argoverse 2 trajectories from the 30 to 110 frames

### ISSUE THREAD

**Issue by tjyuyao** [vita-epfl/UniTraj#19]
Thank you for your excellent work. Now I am considering moving from my original Argoverse 2 codebase to UniTraj. But I meet a problem.

The Argoverse 2 benchmark uses 5 seconds of past and 6 seconds future trajectory. To be able to compare with other model trained on Argoverse 2 or evaluate on test split, but also keeps the 8 seconds format of UniTraj, I think it would be a good practice to trim the data starting from 3 second instead of using the first 8 seconds out of 11, thus the 3-5 second trajectory is the history trajectory, and the future part is aligned with the Argoverse 2 official. I am willing to help on adding this feature to UniTraj, if you also think this is proper. But now I need some suggestions on whether this is acceptable, and what details do I need to know to implement this in case I miss them.

Any advises and discussions are welcome.

**Comment by Alan-LanFeng** [comment]
Hi,

Yes, I think this change is valuable. And I appreciate that you can contribute to this project!

My suggestions:
change 'past_len' and 'future_len' keys in the config to:
start_time_step, current_time_step, and end_time_step. So that the users can decide which part of the trajectories can be used.

[start_time_step, current_time_step] shall be used as input and (current_time_step,end_time_step] shall be used as ground truth.

Since the trajectories have been interpolated to 10Hz by Scenarionet, maybe you need to find which index is 'current_time_step' in the Argoverse dataset. It could be around 50 but I'm not quite sure.

Any further questions are welcome.

**Comment by tjyuyao** [comment]
If we want to load mixed sources from e.g. Argoverse 2 and nuScenes, it seems not easy to specify these config keys. I wonder whether preprocessing the result from scenarionet by trimming it before UniTraj dataset caching could be a better solution.

**Comment by Alan-LanFeng** [comment]
Since scenarionet preprocessing typically takes a long time, I suggest not modifying that part.

You can change the configs I mentioned into list format like 'max_data_num'. So that you can define them for each of the dataset

**Comment by tjyuyao** [comment]
I have submitted an implementation through the pull request. Please review the code.
I have tested training MTR with `past_pos=[30]` on Argoverse, currently I did not spot any runtime fatal issue.
I have no experience on handling the dynamic map events, which is missing in Argoverse 2, so I may need more time to figure out what to do and now I leave it untouched.

**Comment by Alan-LanFeng** [comment]
Thanks for your contribution.
